[package]
name = "ice-box"
version.workspace = true
description = "ice-box desktop shell (Tauri)"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "ice_box_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png"] }
tauri-plugin-opener = "2"
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
ice-core = { workspace = true }
ice-proxy-sys = { workspace = true }
ice-config = { workspace = true }
ice-subscription = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
fs2 = "0.4"
