import "./style.css";

document.querySelector("#root").innerHTML = `
  <header class="site-nav">
    <a class="brand" href="#top"><span class="brand-mark">✦</span><span>ice-box</span></a>
    <nav class="site-links"><a href="#demo">Product</a><a href="#how">How it works</a><a href="#docs">Docs</a></nav>
    <a class="nav-github" href="https://github.com/yilong-musk/ice-box" target="_blank" rel="noreferrer">GitHub ↗</a>
  </header>
  <main id="top">
    <section class="hero page-wrap">
      <div class="hero-copy"><p class="eyebrow"><span class="eyebrow-dot"></span> OPEN SOURCE · DESKTOP PROXY CLIENT</p><h1>A calmer way to<br><em>route the internet.</em></h1><p class="hero-lede">ice-box gives macOS and Windows a focused control surface for nodes, rules, subscriptions, and live traffic — powered by sing-box.</p><div class="hero-actions"><a class="button button-dark" href="#demo">Try the live demo ↓</a><a class="text-link" href="https://github.com/yilong-musk/ice-box" target="_blank" rel="noreferrer">View source ↗</a></div><div class="hero-meta"><span><b class="status-dot green"></b> v0.1.3</span><span>MIT licensed</span><span>macOS · Windows</span></div></div>
      <div class="hero-aside"><div class="signal-card"><div class="signal-top"><span>NETWORK / 01</span><span>ICE-BOX</span></div><div class="signal-grid"><i></i><i></i><i></i><b class="node-a"></b><b class="node-b"></b><b class="node-c"></b></div><div class="signal-bottom"><span>private by default</span><strong>↗</strong></div></div></div>
    </section>
    <section class="demo-section page-wrap" id="demo"><div class="section-intro"><div><p class="eyebrow">THE PRODUCT, IN MOTION</p><h2>The real interface,<br><em>inside the website.</em></h2></div><p>Everything below is the actual desktop frontend from this repository. The browser demo uses a local mock API so you can interact with the UI without installing the native app.</p></div><div class="app-window"><div class="window-bar"><span class="window-dots"><i></i><i></i><i></i></span><strong>ice-box <small>live product demo</small></strong><span>v0.1.3</span></div><iframe title="ice-box real desktop frontend demo" src="./demo.html"></iframe></div></section>
    <section class="principles page-wrap" id="how"><div class="section-intro compact"><p class="eyebrow">BUILT AROUND CLARITY</p><h2>Small surface.<br><em>Serious control.</em></h2></div><div class="principle-grid"><article><span>01</span><h3>One focused workspace</h3><p>Every important action is close: choose a node, change a mode, inspect a rule, or see what is happening right now.</p></article><article><span>02</span><h3>Rules you can read</h3><p>Human-sized tables and explicit state make it easy to understand why traffic took a particular path.</p></article><article><span>03</span><h3>Native where it counts</h3><p>A lightweight Tauri shell keeps the UI fast while sing-box handles the networking work underneath.</p></article></div></section>
    <section class="architecture page-wrap" id="docs"><div><p class="eyebrow">UNDER THE SURFACE</p><h2>Designed to stay<br><em>out of your way.</em></h2><p>ice-box combines a native desktop shell with a small Rust workspace. The interface talks to a local core, so settings and traffic stay on your machine.</p><a class="text-link" href="https://github.com/yilong-musk/ice-box#readme" target="_blank" rel="noreferrer">Read the architecture notes ↗</a></div><div class="arch-diagram"><div class="arch-box top">ice-box UI <small>React + Tauri</small></div><i></i><div class="arch-row"><div class="arch-box">ice-core <small>status · traffic · reload</small></div><div class="arch-box">ice-subscription <small>Clash · sing-box · links</small></div></div><i></i><div class="arch-box bottom">sing-box <small>routing engine</small></div></div></section>
    <section class="final-cta page-wrap"><p class="eyebrow">READY WHEN YOU ARE</p><h2>Make the network<br><em>feel understandable.</em></h2><a class="button button-dark" href="https://github.com/yilong-musk/ice-box" target="_blank" rel="noreferrer">Get ice-box on GitHub ↗</a></section>
  </main>
  <footer class="site-footer page-wrap"><span>© 2026 ice-box</span><span>Made for quieter networks.</span><a href="https://github.com/yilong-musk/ice-box" target="_blank" rel="noreferrer">github.com/yilong-musk/ice-box ↗</a></footer>
`;
