#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Bump the ice-box version across every version source and refresh Cargo.lock.
# Usage: scripts/bump-version.sh 0.1.1
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

NEW_VERSION="${1:-}"
if [[ ! "$NEW_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]]; then
  echo "usage: $0 <semver, e.g. 0.1.1>" >&2
  exit 1
fi

CARGO_TOML="Cargo.toml"
PACKAGE_JSON="apps/desktop/package.json"
TAURI_CONF="apps/desktop/src-tauri/tauri.conf.json"
MOBILE_PACKAGE_JSON="apps/mobile/package.json"
MOBILE_TAURI_CONF="apps/mobile/src-tauri/tauri.conf.json"
ANDROID_PROPERTIES="apps/mobile/src-tauri/gen/android/app/tauri.properties"

bump_key() {
  local file="$1"
  local pattern="$2"
  if ! grep -q "^${pattern}\"[0-9][^\"]*\"" "$file"; then
    echo "pattern '$pattern' not found in $file" >&2
    exit 1
  fi
  PATTERN="$pattern" NEW_VERSION="$NEW_VERSION" perl -pi \
    -e 's/^($ENV{PATTERN})"[0-9][^"]*"/$1"$ENV{NEW_VERSION}"/' "$file"
}

bump_key "$CARGO_TOML" 'version = '
bump_key "$PACKAGE_JSON" '  "version": '
bump_key "$TAURI_CONF" '  "version": '
bump_key "$MOBILE_PACKAGE_JSON" '  "version": '
bump_key "$MOBILE_TAURI_CONF" '  "version": '

# Same integer Tauri writes when bundle.android.versionCode is unset:
# major * 1000000 + minor * 1000 + patch. A pre-release suffix does not
# change it, so do not publish a pre-release and a final build of the same triple.
ANDROID_VERSION_CODE="$(bash "$ROOT/scripts/android-version-code.sh" "$NEW_VERSION")"
python3 - "$MOBILE_TAURI_CONF" "$ANDROID_VERSION_CODE" <<'PY'
import pathlib, re, sys

path, code = sys.argv[1], sys.argv[2]
file = pathlib.Path(path)
text = file.read_text()
if re.search(r'"versionCode"\s*:', text):
    text, count = re.subn(r'("versionCode"\s*:\s*)\d+', rf"\g<1>{code}", text, count=1)
    if count != 1:
        raise SystemExit(f"failed to update versionCode in {path}")
else:
    needle = '"debugApplicationIdSuffix": ".debug"'
    insert = needle + f',\n      "versionCode": {code}'
    if needle not in text:
        raise SystemExit(f"android.versionCode anchor not found in {path}")
    text = text.replace(needle, insert, 1)
file.write_text(text)
PY
cat >"$ANDROID_PROPERTIES" <<EOF
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=${NEW_VERSION}
tauri.android.versionCode=${ANDROID_VERSION_CODE}
EOF

echo "bumped to $NEW_VERSION (Android versionCode $ANDROID_VERSION_CODE):"
grep -n '^version' "$CARGO_TOML"
grep -n '"version"' "$PACKAGE_JSON"
grep -n '"version"' "$TAURI_CONF"
grep -n '"version"' "$MOBILE_PACKAGE_JSON"
grep -n '"version"' "$MOBILE_TAURI_CONF"
grep -n 'versionCode' "$MOBILE_TAURI_CONF"
grep -n 'tauri.android' "$ANDROID_PROPERTIES"

echo "== refreshing Cargo.lock =="
cargo check --workspace --quiet

echo "bump-version: OK ($NEW_VERSION)"